package main

// maze object ids (names matching names in IDA)
const (
	MAZEOBJ_TILE_FLOOR = iota
	MAZEOBJ_TILE_STUN
	MAZEOBJ_WALL_REGULAR
	MAZEOBJ_WALL_MOVABLE
	MAZEOBJ_WALL_SECRET
	MAZEOBJ_WALL_DESTRUCTABLE
	MAZEOBJ_WALL_RANDOM
	MAZEOBJ_WALL_TRAPCYC1
	MAZEOBJ_WALL_TRAPCYC2
	MAZEOBJ_WALL_TRAPCYC3
	MAZEOBJ_TILE_TRAP1
	MAZEOBJ_TILE_TRAP2
	MAZEOBJ_TILE_TRAP3
	MAZEOBJ_DOOR_HORIZ
	MAZEOBJ_DOOR_VERT
	MAZEOBJ_PLAYERSTART
	MAZEOBJ_EXIT
	MAZEOBJ_EXITTO6
	MAZEOBJ_MONST_GHOST
	MAZEOBJ_MONST_GRUNT
	MAZEOBJ_MONST_DEMON
	MAZEOBJ_MONST_LOBBER
	MAZEOBJ_MONST_SORC
	MAZEOBJ_MONST_AUX_GRUNT
	MAZEOBJ_MONST_DEATH
	MAZEOBJ_MONST_ACID
	MAZEOBJ_MONST_SUPERSORC
	MAZEOBJ_MONST_IT
	MAZEOBJ_GEN_GHOST1
	MAZEOBJ_GEN_GHOST2
	MAZEOBJ_GEN_GHOST3
	MAZEOBJ_GEN_GRUNT1
	MAZEOBJ_GEN_GRUNT2
	MAZEOBJ_GEN_GRUNT3
	MAZEOBJ_GEN_DEMON1
	MAZEOBJ_GEN_DEMON2
	MAZEOBJ_GEN_DEMON3
	MAZEOBJ_GEN_LOBBER1
	MAZEOBJ_GEN_LOBBER2
	MAZEOBJ_GEN_LOBBER3
	MAZEOBJ_GEN_SORC1
	MAZEOBJ_GEN_SORC2
	MAZEOBJ_GEN_SORC3
	MAZEOBJ_GEN_AUX_GRUNT1
	MAZEOBJ_GEN_AUX_GRUNT2
	MAZEOBJ_GEN_AUX_GRUNT3
	MAZEOBJ_TREASURE
	MAZEOBJ_TREASURE_LOCKED
	MAZEOBJ_TREASURE_BAG
	MAZEOBJ_FOOD_DESTRUCTABLE
	MAZEOBJ_FOOD_INVULN
	MAZEOBJ_POT_DESTRUCTABLE
	MAZEOBJ_POT_INVULN
	MAZEOBJ_KEY
	MAZEOBJ_POWER_INVIS
	MAZEOBJ_POWER_REPULSE
	MAZEOBJ_POWER_REFLECT
	MAZEOBJ_POWER_TRANSPORT
	MAZEOBJ_POWER_SUPERSHOT
	MAZEOBJ_POWER_INVULN
	MAZEOBJ_MONST_DRAGON
	MAZEOBJ_HIDDENPOT
	MAZEOBJ_TRANSPORTER
	MAZEOBJ_FORCEFIELDHUB
)

// flags for level
const (
	LFLAG1_ODDANGLE_GHOSTS = 1 << iota
	LFLAG1_ODDANGLE_GRUNTS
	LFLAG1_ODDANGLE_DEMONS
	LFLAG1_ODDANGLE_LOBBERS
	LFLAG1_ODDANGLE_SORCERERS
	LFLAG1_ODDANGLE_AUX_GRUNTS
	LFLAG1_ODDANGLE_DEATHS
	LFLAG1_INVIS_TRAPWALLS
)

const (
	LFLAG2_FAST_GHOSTS = 1 << iota
	LFLAG2_FAST_GRUNTS
	LFLAG2_FAST_DEMONS
	LFLAG2_FAST_LOBBERS
	LFLAG2_FAST_SORCERERS
	LFLAG2_FAST_AUX_GRUNTS
	LFLAG2_FAST_DEATHS
	LFLAG2_INVIS_ALLWALLS
)

const (
	LFLAG3_RANDOMFOOD_MASK  = 0x7
	LFLAG3_WALLS_CYCLIC     = 0x8
	LFLAG3_WALLS_DELETABLE1 = 0x10
	LFLAG3_WALLS_DELETABLE2 = 0x20
	LFLAG3_EXIT_MOVES       = 0x40
	LFLAG3_EXIT_CHOOSEONE   = 0x80
)

const (
	LFLAG4_SHOTS_STUN = 1 << iota
	LFLAG4_SHOTS_HURT
	LFLAG4_TRAPS_LOCAL
	LFLAG4_TRAPS_RANDOM
	LFLAG4_WRAP_V
	LFLAG4_WRAP_H
	LFLAG4_EXIT_FAKE
	LFLAG4_PLAYER_OFFSCREEN
)
